# -*- coding: utf-8 -*-
"""Welcome To Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
student_data_df = pd.read_csv('/content/StudentsPerformance.csv')
student_data_df

student_data_df['gender'].value_counts()

student_data_df["parental level of education"].value_counts()

student_data_df.mean().plot.bar()
plt.show()

student_data_df.groupby(["test preparation course"]).mean().plot.bar()
plt.show()

grouped = student_data_df.groupby(['gender', 'test preparation course'])
mean_scores = grouped[['math score', 'reading score', 'writing score']].mean()
print(mean_scores)

df = pd.read_csv('/content/StudentsPerformance.csv')
df_sorted = df.sort_values(by='math score', ascending=False)
top_25_percent_cutoff = int(len(df_sorted) * 0.25)
bonus_points = 5
df_sorted.loc[df_sorted.index < top_25_percent_cutoff, 'math score'] += bonus_points
print(df_sorted.head(top_25_percent_cutoff))