# -*- coding: utf-8 -*-
"""Welcome to Colaboratory

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# New section
"""

# importing from libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# reading an excel file
df=pd.read_excel('/content/iris.xls')

#displaying the columns
print(df.columns)

#to calculate mean of each column
column_means=df.mean()
print(column_means)

#checking null values present
df.isnull()

#visualization using dataset
#type 1
df.plot()

#type 2
df.plot.box()

#type 3
df.plot.bar()
plt.xticks(rotation=60)

df.plot.hist()